### ISSUE TITLE
Requirement 5: Add Spy Enemies List Functionality 

### ISSUE THREAD

**Issue by GuessImNick** [nss-evening-cohort-18/SpyDuh-Catwoman#9]
As a SpyDuh member
I want to keep track of my enemies
So that I know who to watch out for

### Tasks
- [x] Create an enemy list in the Spy model
- [x] Create a method inside of the SpyController to view enemies in the list
- [ ] Create a method inside of the SpyController to add enemies to the list
- [ ] Create a method inside of the SpyController to remove enemies to the list
- [ ] Create methods in the SpyRepository for each new method added in this Issue
- [ ] Update ISpyRepository interface with each new method
